<template>
  <div class="works">
    <v-row>
      <v-col cols="6" sm="4" md="4" lg="4" xl="3" xxl="3" v-for="(item, i) in pictures" :key="i" class="works-list">
        <v-card color="#032a57" height="90%" class="links">
          <v-img v-bind:src="item.src"></v-img>
          <v-card-title class="works-list-title">{{
            item.title
          }}</v-card-title>
          <v-card-text class="works-list-description">{{
            item.description
          }}</v-card-text>
          <a :href="item.linkNicoNico" target=”_blank” v-if="item.linkNicoNico !== ''"><v-icon size="24">mdi-television-classic</v-icon></a>
          <v-icon color="rgba(226,234,255,0.4)" size="24" v-else>mdi-television-classic</v-icon>
          <a :href="item.linkYouTube" target=”_blank” v-if="item.linkYouTube !== ''"><v-icon size="24">mdi-youtube</v-icon></a>
          <v-icon color="rgba(226,234,255,0.4)" size="24" v-else>mdi-youtube</v-icon>
          <a :href="item.linkSoundCloud" target=”_blank” v-if="item.linkSoundCloud !== ''"><v-icon size="24">mdi-soundcloud</v-icon></a>
          <v-icon color="rgba(226,234,255,0.4)" size="24" v-else>mdi-soundcloud</v-icon>
          <div class="my-3"></div>
        </v-card>
      </v-col>
    </v-row>
  </div>
</template>

<script>

export default {
  name: "MusicView",
  components: {
  },

  data: () => ({
    pictures: [
      {
        src: require("../assets/music/oth.webp"),
        linkNicoNico: "",
        linkYouTube: "",
        linkSoundCloud: "https://soundcloud.com/im3py/aqn",
        title: "A quiet night",
        description: "2018~9年制作。\n安眠用。",
      },
      {
        src: require("../assets/music/天啓.webp"),
        linkNicoNico: "",
        linkYouTube: "",
        linkSoundCloud: "https://soundcloud.com/im3py/rev",
        title: "天啓",
        description: "2019年制作の曲のリメイク。",
      },
      {
        src: require("../assets/music/flowerfloated.webp"),
        linkNicoNico: "",
        linkYouTube: "",
        linkSoundCloud: "",
        title: "海に花を流そう",
        description: "2019年7月制作。\n2hDTMの作品。",
      },
      {
        src: require("../assets/music/潜水.webp"),
        linkNicoNico: "",
        linkYouTube: "",
        linkSoundCloud: "",
        title: "潜水",
        description: "2020年1月制作。別名義でコンピに出したもの。",
      },
      {
        src: require("../assets/music/spring.webp"),
        linkNicoNico: "",
        linkYouTube: "",
        linkSoundCloud: "",
        title: "春は芽吹きの頃",
        description: "2020年4月制作。\nループBGM。",
      },
      {
        src: require("../assets/music/fan.webp"),
        linkNicoNico: "",
        linkYouTube: "",
        linkSoundCloud: "https://soundcloud.com/im3py/fan",
        title: "扇風機",
        description: "2020年6月制作。\nDTM交流会の作品。",
      },
      {
        src: require("../assets/music/fireflower.webp"),
        linkNicoNico: "",
        linkYouTube: "",
        linkSoundCloud: "https://soundcloud.com/im3py/syr",
        title: "イチゴシロップ",
        description: "2020年7月制作。\n2hDTMの作品。",
      },
      {
        src: require("../assets/music/彗星天輝.webp"),
        linkNicoNico: "https://www.nicovideo.jp/watch/sm37781027",
        linkYouTube: "https://www.youtube.com/watch?v=-dDJJft9zG8",
        linkSoundCloud: "https://soundcloud.com/im3py/com",
        title: "彗星は天に輝く",
        description: "2020年11月制作。\nボカロ初投稿。",
      },
      {
        src: require("../assets/music/革命前夜.webp"),
        linkNicoNico: "https://www.nicovideo.jp/watch/sm37781074",
        linkYouTube: "https://www.youtube.com/watch?v=iDmr_MPPczk",
        linkSoundCloud: "https://soundcloud.com/im3py/eve",
        title: "革命前夜",
        description: "2020年11月制作。KSMパッケージ「Serene Life On Waterfront」収録曲。",
      },
      {
        src: require("../assets/music/愛の形.webp"),
        linkNicoNico: "https://www.nicovideo.jp/watch/sm37936603",
        linkYouTube: "https://www.youtube.com/watch?v=wnukOgYGMIY",
        linkSoundCloud: "https://soundcloud.com/im3py/frm",
        title: "愛の形",
        description: "2021年1月制作。\n歌詞は借り物。",
      },
      {
        src: require("../assets/music/kick.webp"),
        linkNicoNico: "https://www.nicovideo.jp/watch/sm38124494",
        linkYouTube: "https://www.youtube.com/watch?v=9wC3t0MXp8Q",
        linkSoundCloud: "https://soundcloud.com/im3py/kic",
        title: "kick",
        description: "2021年1月制作。自棄になったときに書いたもの。",
      },
      {
        src: require("../assets/music/魔王爆破.webp"),
        linkNicoNico: "",
        linkYouTube: "",
        linkSoundCloud: "https://soundcloud.com/im3py/dvl",
        title: "魔王が地球を爆破させるようです",
        description: "2021年2月制作。\nDTM交流会の作品。",
      },
      {
        src: require("../assets/music/風そよぐ.webp"),
        linkNicoNico: "",
        linkYouTube: "",
        linkSoundCloud: "https://soundcloud.com/im3py/brt",
        title: "風そよぐ",
        description: "2021年3月制作。新入生プロジェクトで作った曲。",
      },
      {
        src: require("../assets/music/thanatos_hello.webp"),
        linkNicoNico: "",
        linkYouTube: "",
        linkSoundCloud: "https://soundcloud.com/im3py/hth",
        title: "Hello, Thanatos",
        description: "2021年3月制作。\nDTM講習会用に書いたもの。",
      },
      {
        src: require("../assets/music/街灯.webp"),
        linkNicoNico: "https://www.nicovideo.jp/watch/sm38614695",
        linkYouTube: "https://www.youtube.com/watch?v=OejtKCCnQmE",
        linkSoundCloud: "https://soundcloud.com/im3py/stl",
        title: "街灯のない道路",
        description: "2021年4月制作。\nMIS.Wに入って初めての発表会で出したもの。",
      },
      {
        src: require("../assets/music/徘徊幽霊.webp"),
        linkNicoNico: "https://www.nicovideo.jp/watch/sm38633207",
        linkYouTube: "https://www.youtube.com/watch?v=rdFwLuDjU3Q",
        linkSoundCloud: "https://soundcloud.com/im3py/wan",
        title: "徘徊幽霊",
        description: "2021年4月制作。\nボカコレ投稿作。",
      },
      {
        src: require("../assets/music/my_name.webp"),
        linkNicoNico: "",
        linkYouTube: "",
        linkSoundCloud: "",
        title: "わたしの名前",
        description: "2021年5月制作。\nDTM交流会で書いた気がする。",
      },
      {
        src: require("../assets/music/CDjacket_i2.webp"),
        linkNicoNico: "",
        linkYouTube: "",
        linkSoundCloud: "",
        title: "つるぎのまい",
        description: "2021年6月制作。\nno description",
      },
      {
        src: require("../assets/noimage.webp"),
        linkNicoNico: "",
        linkYouTube: "",
        linkSoundCloud: "",
        title: "さよならを言わないで",
        description: "2021年7月制作。\nMIS.W学祭コンピの曲。",
      },
      {
        src: require("../assets/music/Poyo-poyo dreamer.webp"),
        linkNicoNico: "",
        linkYouTube: "",
        linkSoundCloud: "https://soundcloud.com/im3py/ppd",
        title: "Poyo-poyo Dreamer!",
        description: "2021年7月制作。Kawaii曲を作りたかった。",
      },
      {
        src: require("../assets/music/ぼくらの世界_400x400.webp"),
        linkNicoNico: "https://www.nicovideo.jp/watch/sm39313776",
        linkYouTube: "https://www.youtube.com/watch?v=UcJe11pKSpw",
        linkSoundCloud: "https://soundcloud.com/im3py/myw",
        title: "ぼくらの世界",
        description: "2021年7月制作。第71回東北大学祭テーマソング応募作。",
      },
      {
        src: require("../assets/music/CDjacket_i2.webp"),
        linkNicoNico: "",
        linkYouTube: "",
        linkSoundCloud: "",
        title: "語らいたいな",
        description: "2021年8月制作。\nno description",
      },
      {
        src: require("../assets/music/Vaccine-O.webp"),
        linkNicoNico: "",
        linkYouTube: "",
        linkSoundCloud: "https://soundcloud.com/im3py/vco",
        title: "Vaccine-O",
        description: "2021年9月制作。\n「君の注射に超夢中」BGM。",
      },
      {
        src: require("../assets/music/Vaccination.webp"),
        linkNicoNico: "",
        linkYouTube: "",
        linkSoundCloud: "https://soundcloud.com/im3py/vcn",
        title: "Vaccination",
        description: "2021年9月制作。\n「君の注射に超夢中」BGMその2。",
      },
      {
        src: require("../assets/music/夢破れて.webp"),
        linkNicoNico: "",
        linkYouTube: "",
        linkSoundCloud: "https://soundcloud.com/im3py/idd",
        title: "夢破れて",
        description: "2021年9月制作。\n「君の注射に超夢中」BGMその3。",
      },
      {
        src: require("../assets/noimage.webp"),
        linkNicoNico: "",
        linkYouTube: "https://www.youtube.com/live/Kh3NS6677-8&t=11072",
        linkSoundCloud: "",
        title: "対峙",
        description: "2021年9月制作。夏休みアレンジ祭参加作。",
      },
      {
        src: require("../assets/music/coffee_moon.webp"),
        linkNicoNico: "",
        linkYouTube: "",
        linkSoundCloud: "",
        title: "コーヒーに浮かぶ月",
        description: "2021年9月制作。\nDTM交流会の曲。",
      },
      {
        src: require("../assets/music/感傷レイニー.webp"),
        linkNicoNico: "https://www.nicovideo.jp/watch/sm39474856",
        linkYouTube: "https://www.youtube.com/watch?v=TU6irObfV_Q",
        linkSoundCloud: "https://soundcloud.com/im3py/stm",
        title: "感傷レイニー",
        description: "2021年11月制作。ボカコレ2021秋、MIS.Wコンピ参加作。",
      },
      {
        src: require("../assets/music/逃避癖.webp"),
        linkNicoNico: "https://www.nicovideo.jp/watch/sm39588593",
        linkYouTube: "https://www.youtube.com/watch?v=vqEwHqsQkug",
        linkSoundCloud: "https://soundcloud.com/im3py/esc",
        title: "逃避癖",
        description: "2021年11月制作。MIS.Wボカロ企画参加作。",
      },
      {
        src: require("../assets/music/Walking_around_sum.webp"),
        linkNicoNico: "",
        linkYouTube: "",
        linkSoundCloud: "https://soundcloud.com/im3py/war",
        title: "Walking around",
        description: "2021年12月制作。",
      },
      {
        src: require("../assets/music/Surfing Dreamer.webp"),
        linkNicoNico: "",
        linkYouTube: "",
        linkSoundCloud: "https://soundcloud.com/im3py/sfd",
        title: "Surfing Dreamer!",
        description: "2021年12月制作。",
      },
      {
        src: require("../assets/music/make_it_so_wonderful_sum.webp"),
        linkNicoNico: "",
        linkYouTube: "",
        linkSoundCloud: "https://soundcloud.com/im3py/miw",
        title: "Make It So Wonderful!",
        description: "2022年1月制作。MIS.W引退企画参加作。",
      },
      {
        src: require("../assets/music/森の妖怪伝説.webp"),
        linkNicoNico: "",
        linkYouTube: "",
        linkSoundCloud: "https://soundcloud.com/im3py/wap",
        title: "森の妖怪伝説",
        description: "2022年1月制作。",
      },
      {
        src: require("../assets/music/Ifpweak_sc_sum.webp"),
        linkNicoNico: "https://www.nicovideo.jp/watch/sm39994044",
        linkYouTube: "",
        linkSoundCloud: "",
        title: "海とメランコリー",
        description: "2022年2月制作。",
      },
      {
        src: require("../assets/music/Canopus_sum.webp"),
        linkNicoNico: "",
        linkYouTube: "",
        linkSoundCloud: "https://soundcloud.com/im3py/cnp",
        title: "Canopus",
        description: "2022年2月制作。MIS.Wアレンジ企画参加作。",
      },
      {
        src: require("../assets/music/rain_sum.webp"),
        linkNicoNico: "",
        linkYouTube: "",
        linkSoundCloud: "https://soundcloud.com/im3py/oad",
        title: "こんな日は",
        description: "2022年2月制作。",
      },
      {
        src: require("../assets/music/dissolve.webp"),
        linkNicoNico: "",
        linkYouTube: "https://www.youtube.com/watch?v=jn4uCDeI4o4",
        linkSoundCloud: "",
        title: "Dissolve",
        description: "2022年3月制作。冬休みアレンジ祭参加作。",
      },
      {
        src: require("../assets/music/嘆き_sum.webp"),
        linkNicoNico: "https://www.nicovideo.jp/watch/sm40192284",
        linkYouTube: "https://www.youtube.com/watch?v=MI4GBc7XKak",
        linkSoundCloud: "https://soundcloud.com/im3py/lam",
        title: "嘆き",
        description: "2022年3月制作。\n天使はショタがち。",
      },
      {
        src: require("../assets/music/enmity.webp"),
        linkNicoNico: "",
        linkYouTube: "",
        linkSoundCloud: "https://soundcloud.com/im3py/enm",
        title: "Enmity",
        description: "2022年4月制作。聴き返せなくてPV制作を断念。",
      },
      {
        src: require("../assets/music/12percent.webp"),
        linkNicoNico: "",
        linkYouTube: "",
        linkSoundCloud: "",
        title: "12%とカウンター席",
        description: "2022年5月制作。DTM交流会の曲。",
      },
      {
        src: require("../assets/music/あまあまスロッピー.webp"),
        linkNicoNico: "https://www.nicovideo.jp/watch/sm40618458",
        linkYouTube: "https://www.youtube.com/watch?v=LL3bS6UfPAk",
        linkSoundCloud: "",
        title: "あまあまスロッピー",
        description: "2022年5月制作。〆切直前の曲。",
      },
      {
        src: require("../assets/music/向上心の塊.webp"),
        linkNicoNico: "",
        linkYouTube: "",
        linkSoundCloud: "https://soundcloud.com/im3py/asp",
        title: "向上心の塊",
        description: "2022年5月制作？",
      },
      {
        src: require("../assets/picture/Magical_sum.webp"),
        linkNicoNico: "",
        linkYouTube: "",
        linkSoundCloud: "https://soundcloud.com/im3py/asp",
        title: "ハートビートダンス",
        description: "2022年7月制作？\n画集のテーマに合わせて書いた。",
      },
      {
        src: require("../assets/music/さよならちゃん_sum.webp"),
        linkNicoNico: "https://www.nicovideo.jp/watch/sm41350173",
        linkYouTube: "https://www.youtube.com/watch?v=afaifgc0AkQ",
        linkSoundCloud: "",
        title: "さよならちゃん",
        description: "2022年11月制作。\nMIS.Wボカロ企画参加作。",
      },
      {
        src: require("../assets/music/maider.webp"),
        linkNicoNico: "https://www.nicovideo.jp/watch/sm41475582",
        linkYouTube: "https://www.youtube.com/watch?v=rkfXM1nSlBc",
        linkSoundCloud: "",
        title: "M'aider",
        description: "2022年12月制作。\n強気に生きたい。",
      },
      {
        src: require("../assets/music/mirror_sum.webp"),
        linkNicoNico: "",
        linkYouTube: "",
        linkSoundCloud: "https://soundcloud.com/im3py/mrr",
        title: "mirror",
        description: "2023年5月制作。一回没にしたけど生存報告のために投稿。",
      },
      {
        src: require("../assets/music/テラーと歯車.webp"),
        linkNicoNico: "https://www.nicovideo.jp/watch/sm42676038",
        linkYouTube: "https://www.youtube.com/watch?v=ajhMVt4Xcfs",
        linkSoundCloud: "",
        title: "テラーと歯車",
        description: "2023年5月制作。院試期間中ずっと聴いてた。",
      },
      {
        src: require("../assets/picture/estazolam_sum.webp"),
        linkNicoNico: "https://www.nicovideo.jp/watch/so42905295",
        linkYouTube: "",
        linkSoundCloud: "",
        title: "エスタゾラム",
        description: "2023年9月制作。\n無色透名祭Ⅱ参加曲。",
      },
      {
        src: require("../assets/music/summer1_ico.webp"),
        linkNicoNico: "",
        linkYouTube: "",
        linkSoundCloud: "https://soundcloud.com/im3py/cnc",
        title: "炭酸抜きの思案",
        description: "2024年4月制作。BGMが必要になったので。",
      },
      {
        src: require("../assets/music/eihwaz_sum.webp"),
        linkNicoNico: "",
        linkYouTube: "",
        linkSoundCloud: "https://soundcloud.com/im3py/ile",
        title: "エイワズの地にて",
        description: "2024年5月制作。サークルのDTM講習会の制作デモ。",
      },
      {
        src: require("../assets/noimage.webp"),
        linkNicoNico: "",
        linkYouTube: "",
        linkSoundCloud: "",
        title: "Coming soon...",
        description: "制作中",
      },
    ],
  }),
};
</script>
